// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const pirate = { url, data: "", y: 0, h: 16, w: 16, x: 0, };
export const pivot_point = { url, data: "", pivot: { y: 7, x: 7, }, y: 0, h: 16, w: 16, x: 16, };
export const nine_slice = { center: { y: 1, h: 14, w: 14, x: 1, }, url, data: "", y: 0, h: 16, w: 16, x: 32, };
export const _let = { url, data: "reserved word", y: 16, h: 16, w: 16, x: 0, };
export const _01 = { url, data: "starts_with_number", y: 16, h: 16, w: 16, x: 16, };