name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip -r typescript-sprites.aseprite-extension typescript-sprites.{lua,aseprite-keys}
      - uses: actions/upload-artifact@v3
        with:
          name: typescript-sprites
          path: typescript-sprites.aseprite-extension
